framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Gtto\Tests\:
    resource: '../../../../tests'

  # -- IMPLEMENTATIONS SELECTOR --
  Gtto\Shared\Domain\Bus\Event\EventBus: '@Gtto\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus'
