services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [Gtto\Mooc\Shared\Infrastructure\Persistence\Doctrine\MoocEntityManagerFactory, create]
    arguments:
      - driver:   '%env(MOOC_DATABASE_DRIVER)%'
        host:     '%env(MOOC_DATABASE_HOST)%'
        port:     '%env(MOOC_DATABASE_PORT)%'
        dbname:   '%env(MOOC_DATABASE_NAME)%'
        user:     '%env(MOOC_DATABASE_USER)%'
        password: '%env(MOOC_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: gtto.database_connection }
    public: true


  # Crushes
  Gtto\Mooc\Crushes\Domain\CrushRepository: '@Gtto\Mooc\Crushes\Infrastructure\Persistence\DoctrineCrushRepository'

  # Moments
  Gtto\Mooc\Moments\Domain\MomentRepository: '@Gtto\Mooc\Moments\Infrastructure\Persistence\DoctrineMomentRepository'

